# Generated by Django 4.0.3 on 2022-04-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='date',
            field=models.DateField(),
        ),
    ]
