# Generated by Django 4.0.3 on 2022-04-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_notificacao_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friendship',
        ),
    ]
