# Generated by Django 4.0.3 on 2022-04-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_friend_friendship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friendship',
            new_name='Amizade',
        ),
    ]
