# Generated by Django 4.0.3 on 2022-05-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_publicacao_gostos_publicacao_nao_gostos_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='num_pubs',
            field=models.IntegerField(default=0),
        ),
    ]
