# Generated by Django 4.0.3 on 2022-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_rename_num_pubs_publicacao_num_coms'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='biografia',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
