# Generated by Django 4.0.3 on 2022-05-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_sala_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.publicacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.utilizador')),
            ],
        ),
    ]
