# Generated by Django 4.0.3 on 2022-05-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_interacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
