# Generated by Django 4.0.3 on 2022-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_utilizador_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='amigos',
            field=models.IntegerField(default=0),
        ),
    ]
