# Generated by Django 4.0.3 on 2022-05-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(default='nao_definido', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilizador',
            name='tel',
            field=models.CharField(default=123123123, max_length=9),
            preserve_default=False,
        ),
    ]
