# Generated by Django 4.0.3 on 2022-05-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_utilizador_email_utilizador_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='email',
        ),
    ]
