#!/bin/bash
clear
while :; do 
    clear
    time=$(date +%x\ %T)
    echo -e "\n____________________Cliniq-IUL____________________"
    echo -e "\n1. Cria pacientes              $time\n2. Cria médicos\n3. Stats\n4. Avalia médicos\n0. Sair\n"
    read -p 'Insira o número de acordo com a operação desejada: ' option
    echo
    case $option in
        0) 
            clear
            break;;
        1) 
            ./cria_pacientes.sh
            read -s -p 'Pressione Enter para continuar';;
        2) 
            read -p 'Insira o nome do médico: ' nome 
            read -p 'Insira o número de cédula profissional: ' num
            read -p 'Insira a especialidade: ' espec
            read -p 'Insira o e-mail: ' mail
            ./cria_medico.sh "${nome}" $num "${espec}" $mail
            read -s -p 'Pressione Enter para continuar';;
        3)
            read -p 'Insira a localidade para pesquisa em pacientes: ' localidade
            read -p 'Insira o saldo para pesquisa em médicos: ' saldo
            ./stats.sh "${localidade}" $saldo
            read -s -p 'Pressione Enter para continuar';;
        4)
            ./avalia_medicos.sh
            read -s -p 'Pressione Enter para continuar';;  
    esac
done
echo -e "A plataforma Cliniq-IUL foi encerrada.\nAté Breve!\n"